---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-media
  namespace: prod-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    namespace: prod-media
    name: media-library
  nfs:
    server: 192.168.1.42
    path: /volume1/Media
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-library
  namespace: prod-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-downloads
  namespace: prod-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    namespace: prod-media
    name: media-downloads
  nfs:
    server: 192.168.1.42
    path: /volume1/Downloads
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-downloads
  namespace: prod-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
