---
releases:
  - name: "bazarr"
    namespace: "media"
    labels:
      chart: "bazarr"
      repo: "local"
      component: "media"
    chart: "../charts/bazarr"
    version: "0.2.0"
    values:
      - image:
          tag: v0.8.4.1-ls66
        bazarr:
          puid: 1031
          guid: 100
          tz: Europe/Paris
          persistence:
            tv:
              enabled: {{ not (eq (requiredEnv "ENV") "testing") }}
              existingClaim: media-library
        ingress:
          annotations:
            traefik.ingress.kubernetes.io/auth-type: "basic"
            traefik.ingress.kubernetes.io/auth-secret: "basicauth"
          enabled: true
          hosts:
            - bazarr.{{ requiredEnv "DOMAIN_NAME" }}
        persistence:
          enabled: true
