---
repositories:
  - name: billimek
    url: https://billimek.com/billimek-charts/

releases:
  - name: "jackett"
    namespace: "prod-media"
    labels:
      chart: "jackett"
      repo: "billimek"
      component: "media"
    chart: "billimek/jackett"
    version: "2.1.1"
    values:
      - image:
          tag: v0.12.1669-ls52
        puid: 1031
        pgid: 100
        ingress:
          annotations:
            traefik.ingress.kubernetes.io/auth-type: "basic"
            traefik.ingress.kubernetes.io/auth-secret: "basicauth"
          enabled: true
          hosts:
            - jackett.{{ requiredEnv "DOMAIN_NAME" }}
        timezone: Europe/Paris
        persistence:
          torrentblackhole:
            enabled: {{ not (eq (requiredEnv "ENV") "testing") }}
            existingClaim: media-downloads
            subPath: torrent-blackhole
