---

repositories:
  - name: longhorn
    url: https://charts.longhorn.io

releases:
  - name: "longhorn"
    namespace: "longhorn-system"
    labels:
      chart: "longhorn"
      repo: "local"
      component: "storage"
    chart: "longhorn/longhorn"
    version: "1.0.2"
    values:
      - ingress:
          annotations:
            traefik.ingress.kubernetes.io/auth-type: "basic"
            traefik.ingress.kubernetes.io/auth-secret: "basicauth"
          enabled: true
          hosts:
            - longhorn.{{ requiredEnv "DOMAIN_NAME" }}
        csi:
          kubeletRootDir: /var/lib/kubelet
        defaultSettings:
          defaultReplicaCount: 2
        persistence:
          defaultClassReplicaCount: 2
