---
releases:
  - name: "longhorn"
    namespace: "longhorn-system"
    labels:
      chart: "longhorn"
      repo: "local"
      component: "storage"
    chart: "../charts/longhorn/chart"
    version: "0.8.0"
    values:
      - ingress:
          annotations:
            traefik.ingress.kubernetes.io/auth-type: "basic"
            traefik.ingress.kubernetes.io/auth-secret: "basicauth"
          enabled: true
          hosts:
            - longhorn.{{ requiredEnv "DOMAIN_NAME" }}
        defaultSettings:
          backupTarget: nfs://{{ requiredEnv "NAS_IP" }}:/volume1/kubernetes_storage/longhorn-backup
        persistence:
          defaultClass: true
