---
repositories:
  - name: itzg
    url: https://itzg.github.io/minecraft-server-charts/

releases:
  - name: "minecraft-latest"
    namespace: "prod-gaming"
    labels:
      chart: "minecraft"
      repo: "stable"
      component: "gaming"
    chart: "itzg/minecraft"
    version: "2.0.2"
    values:
      - imageTag: "multiarch"
        minecraftServer:
          eula: true
          version: "1.15.2"
          motd: "licorne"
          pvp: true
          memory: 1G
          ops: "juldoc,gwen_78"
          whitelist: "juldoc,gwen_78"
          rcon:
            enabled: true
            port: 25575
            password: {{ requiredEnv "RCON_PASSWORD" | quote }}
            serviceType: LoadBalancer
            loadBalancerIP: {{ requiredEnv "METALLB_PROD_IP" }}
            externalTrafficPolicy: Cluster
          serviceType: LoadBalancer
          serviceAnnotations:
            metallb.universe.tf/allow-shared-ip: prod
          loadBalancerIP: {{ requiredEnv "METALLB_PROD_IP" }}
          externalTrafficPolicy: Cluster
        readinessProbe:
          initialDelaySeconds: 120
          failureThreshold: 100
        livenessProbe:
          initialDelaySeconds: 120
          failureThreshold: 100
        resources:
          requests:
            memory: 1Gi
            cpu: 0
        persistence:
          dataDir:
            enabled: true
