---
repositories:
  - name: t3n
    url: https://storage.googleapis.com/t3n-helm-charts

releases:
  - name: "nas-ui"
    namespace: "media"
    labels:
      chart: "external-service"
      repo: "t3n"
      component: "dashboard"
    chart: "t3n/external-service"
    version: "0.2.0"
    values:
      - ingress:
          enabled: true
        addresses:
          - ip: {{ requiredEnv "NAS_IP" }}
        ports:
          - port: 80
            name: http-services
            ingress:
              hosts:
                - host: nas-ui.{{ requiredEnv "DOMAIN_NAME" }}
                  paths:
                    - '/photo'
          - port: 9000
            name: http-minio
            ingress:
              hosts:
                - host: minio.{{ requiredEnv "DOMAIN_NAME" }}
                  paths:
                    - '/'
          - port: 5000
            name: http
            ingress:
              hosts:
                - host: nas-ui.{{ requiredEnv "DOMAIN_NAME" }}
                  paths:
                    - '/'
