---
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: "nfs-client-provisioner"
    namespace: "kube-system"
    labels:
      chart: "nfs-client-provisioner"
      repo: "stable"
      component: "storage"
    chart: "stable/nfs-client-provisioner"
    version: "1.2.8"
    values:
      - image:
          tag: v3.1.0-k8s1.11
        nfs:
          server: {{ requiredEnv "NAS_IP" }}
          path: /volume1/kubernetes_storage
        storageClass:
          defaultClass: {{ not (eq (requiredEnv "ENV") "testing") }}
