---
repositories:
  - name: billimek
    url: https://billimek.com/billimek-charts/

releases:
  - name: "radarr"
    namespace: "prod-media"
    labels:
      chart: "radarr"
      repo: "billimek"
      component: "media"
    chart: "billimek/radarr"
    version: "3.0.0"
    values:
      - image:
          tag: v0.2.0.1450-ls49
        puid: 1031
        pgid: 100
        ingress:
          annotations:
            traefik.ingress.kubernetes.io/auth-type: "basic"
            traefik.ingress.kubernetes.io/auth-secret: "basicauth"
          enabled: true
          hosts:
            - radarr.{{ requiredEnv "DOMAIN_NAME" }}
        timezone: Europe/Paris
        persistence:
          downloads:
            enabled: {{ not (eq (requiredEnv "ENV") "testing") }}
            existingClaim: media-downloads
          movies:
            enabled: {{ not (eq (requiredEnv "ENV") "testing") }}
            existingClaim: media-library
            subPath: Movies
