---
repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: "traefik"
    namespace: "kube-system"
    labels:
      chart: "traefik"
      repo: "stable"
      component: "ingress"
    chart: "stable/traefik"
    version: "1.86.1"
    values:
      - rbac:
          enabled: true
        dashboard:
          enabled: true
          domain: "traefik.{{ requiredEnv "DOMAIN_NAME" }}"
          auth:
            basic:
              {{ requiredEnv "TRAEFIK_USER" }}: "{{ requiredEnv "TRAEFIK_PASS" }}"
        loadBalancerIP: {{ requiredEnv "METALLB_PROD_IP" }}
        externalTrafficPolicy: Cluster
        service:
          annotations:
            metallb.universe.tf/allow-shared-ip: prod
        ssl:
          enabled: true
          enforced: true
          permanentRedirect: true
        acme:
          logging: true
          enabled: true
          staging: false
          email: "julien.doche@gmail.com"
          challengeType: dns-01
          resolvers:
            - ns1.digitalocean.com
            - ns2.digitalocean.com
            - ns3.digitalocean.com
          dnsProvider:
            name: digitalocean
            digitalocean:
              DO_AUTH_TOKEN: {{ requiredEnv "DO_AUTH_TOKEN" }}
          domains:
            enabled: true
            domainsList:
              - main: "*.{{ requiredEnv "DOMAIN_NAME" }}"
          persistence:
            enabled: true
            storageClass: longhorn
