---
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: "traefik"
    namespace: "kube-system"
    labels:
      chart: "traefik"
      repo: "local"
      component: "ingress"
    chart: "../charts/traefik-helm-chart/traefik"
    version: "3.3.3"
    values:
      - dashboard:
          enable: true
          ingressRoute: true
          domain: "traefik.{{ requiredEnv "DOMAIN_NAME" }}"
          auth:
            basic:
              {{ requiredEnv "TRAEFIK_USER" }}: "{{ requiredEnv "TRAEFIK_PASS" }}"
        ssl:
          enabled: true
          enforced: true
          permanentRedirect: true
        acme:
          logging: true
          enabled: true
          staging: false
          email: "julien.doche@gmail.com"
          challengeType: dns-01
          resolvers:
            - ns1.digitalocean.com
            - ns2.digitalocean.com
            - ns3.digitalocean.com
          dnsProvider:
            name: digitalocean
            digitalocean:
              DO_AUTH_TOKEN: {{ requiredEnv "DO_AUTH_TOKEN" }}
          domains:
            enabled: true
            domainsList:
              - main: "*.{{ requiredEnv "DOMAIN_NAME" }}"
          persistence:
            enabled: true
            storageClass: local-path
